/*
 * generated by Xtext 2.25.0
 */
package it.disim.mde.loreand.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UberDslUiModule extends AbstractUberDslUiModule {

	public UberDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
