/*
 * generated by Xtext 2.25.0
 */
package it.disim.mde.loreand.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.disim.mde.loreand.xtext.UberDslRuntimeModule;
import it.disim.mde.loreand.xtext.UberDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class UberDslIdeSetup extends UberDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UberDslRuntimeModule(), new UberDslIdeModule()));
	}
	
}
