/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class CompanyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Company");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCompanyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCompanyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cManagerKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cManagerAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cManagerEStringParserRuleCall_4_1_0 = (RuleCall)cManagerAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAddressKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAddressAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAddressEStringParserRuleCall_5_1_0 = (RuleCall)cAddressAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCustomersKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cCustomersAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cCustomersCustomerParserRuleCall_6_2_0 = (RuleCall)cCustomersAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cCustomersAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cCustomersCustomerParserRuleCall_6_3_1_0 = (RuleCall)cCustomersAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cRidersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cRidersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cRidersRiderParserRuleCall_7_2_0 = (RuleCall)cRidersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cRidersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cRidersRiderParserRuleCall_7_3_1_0 = (RuleCall)cRidersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cRoutesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cRoutesAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cRoutesRouteParserRuleCall_8_2_0 = (RuleCall)cRoutesAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cRoutesAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cRoutesRouteParserRuleCall_8_3_1_0 = (RuleCall)cRoutesAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Company returns Company:
		//    {Company}
		//    'Company'
		//    name=EString
		//    '{'
		//        ('manager' manager=EString)?
		//        ('address' address=EString)?
		//        ('customers' '{' customers+=Customer ( "," customers+=Customer)* '}' )?
		//        ('riders' '{' riders+=Rider ( "," riders+=Rider)* '}' )?
		//        ('routes' '{' routes+=Route ( "," routes+=Route)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Company}
		//'Company'
		//name=EString
		//'{'
		//    ('manager' manager=EString)?
		//    ('address' address=EString)?
		//    ('customers' '{' customers+=Customer ( "," customers+=Customer)* '}' )?
		//    ('riders' '{' riders+=Rider ( "," riders+=Rider)* '}' )?
		//    ('routes' '{' routes+=Route ( "," routes+=Route)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Company}
		public Action getCompanyAction_0() { return cCompanyAction_0; }
		
		//'Company'
		public Keyword getCompanyKeyword_1() { return cCompanyKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('manager' manager=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'manager'
		public Keyword getManagerKeyword_4_0() { return cManagerKeyword_4_0; }
		
		//manager=EString
		public Assignment getManagerAssignment_4_1() { return cManagerAssignment_4_1; }
		
		//EString
		public RuleCall getManagerEStringParserRuleCall_4_1_0() { return cManagerEStringParserRuleCall_4_1_0; }
		
		//('address' address=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'address'
		public Keyword getAddressKeyword_5_0() { return cAddressKeyword_5_0; }
		
		//address=EString
		public Assignment getAddressAssignment_5_1() { return cAddressAssignment_5_1; }
		
		//EString
		public RuleCall getAddressEStringParserRuleCall_5_1_0() { return cAddressEStringParserRuleCall_5_1_0; }
		
		//('customers' '{' customers+=Customer ( "," customers+=Customer)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'customers'
		public Keyword getCustomersKeyword_6_0() { return cCustomersKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//customers+=Customer
		public Assignment getCustomersAssignment_6_2() { return cCustomersAssignment_6_2; }
		
		//Customer
		public RuleCall getCustomersCustomerParserRuleCall_6_2_0() { return cCustomersCustomerParserRuleCall_6_2_0; }
		
		//( "," customers+=Customer)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//customers+=Customer
		public Assignment getCustomersAssignment_6_3_1() { return cCustomersAssignment_6_3_1; }
		
		//Customer
		public RuleCall getCustomersCustomerParserRuleCall_6_3_1_0() { return cCustomersCustomerParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('riders' '{' riders+=Rider ( "," riders+=Rider)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'riders'
		public Keyword getRidersKeyword_7_0() { return cRidersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//riders+=Rider
		public Assignment getRidersAssignment_7_2() { return cRidersAssignment_7_2; }
		
		//Rider
		public RuleCall getRidersRiderParserRuleCall_7_2_0() { return cRidersRiderParserRuleCall_7_2_0; }
		
		//( "," riders+=Rider)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//riders+=Rider
		public Assignment getRidersAssignment_7_3_1() { return cRidersAssignment_7_3_1; }
		
		//Rider
		public RuleCall getRidersRiderParserRuleCall_7_3_1_0() { return cRidersRiderParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//('routes' '{' routes+=Route ( "," routes+=Route)* '}' )?
		public Group getGroup_8() { return cGroup_8; }
		
		//'routes'
		public Keyword getRoutesKeyword_8_0() { return cRoutesKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//routes+=Route
		public Assignment getRoutesAssignment_8_2() { return cRoutesAssignment_8_2; }
		
		//Route
		public RuleCall getRoutesRouteParserRuleCall_8_2_0() { return cRoutesRouteParserRuleCall_8_2_0; }
		
		//( "," routes+=Route)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//routes+=Route
		public Assignment getRoutesAssignment_8_3_1() { return cRoutesAssignment_8_3_1; }
		
		//Route
		public RuleCall getRoutesRouteParserRuleCall_8_3_1_0() { return cRoutesRouteParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class CustomerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Customer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCustomerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cSurnameKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSurnameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSurnameEStringParserRuleCall_6_0 = (RuleCall)cSurnameAssignment_6.eContents().get(0);
		private final Keyword cEmailKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cEmailAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cEmailEStringParserRuleCall_8_0 = (RuleCall)cEmailAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cSubscriptionDateKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cSubscriptionDateAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cSubscriptionDateEStringParserRuleCall_9_1_0 = (RuleCall)cSubscriptionDateAssignment_9_1.eContents().get(0);
		private final Keyword cExpirationDateKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cExpirationDateAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cExpirationDateEStringParserRuleCall_11_0 = (RuleCall)cExpirationDateAssignment_11.eContents().get(0);
		private final Keyword cStatusKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cStatusAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cStatusCustomerStatusEnumRuleCall_13_0 = (RuleCall)cStatusAssignment_13.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cRoutesKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_14_1 = (Keyword)cGroup_14.eContents().get(1);
		private final Assignment cRoutesAssignment_14_2 = (Assignment)cGroup_14.eContents().get(2);
		private final CrossReference cRoutesRouteCrossReference_14_2_0 = (CrossReference)cRoutesAssignment_14_2.eContents().get(0);
		private final RuleCall cRoutesRouteEStringParserRuleCall_14_2_0_1 = (RuleCall)cRoutesRouteCrossReference_14_2_0.eContents().get(1);
		private final Group cGroup_14_3 = (Group)cGroup_14.eContents().get(3);
		private final Keyword cCommaKeyword_14_3_0 = (Keyword)cGroup_14_3.eContents().get(0);
		private final Assignment cRoutesAssignment_14_3_1 = (Assignment)cGroup_14_3.eContents().get(1);
		private final CrossReference cRoutesRouteCrossReference_14_3_1_0 = (CrossReference)cRoutesAssignment_14_3_1.eContents().get(0);
		private final RuleCall cRoutesRouteEStringParserRuleCall_14_3_1_0_1 = (RuleCall)cRoutesRouteCrossReference_14_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_14_4 = (Keyword)cGroup_14.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Customer returns Customer:
		//    'Customer'
		//    id=EString
		//    '{'
		//        'name' name=EString
		//        'surname' surname=EString
		//        'email' email=EString
		//        ('subscriptionDate' subscriptionDate=EString)?
		//        'expirationDate' expirationDate=EString
		//        'status' status=CustomerStatus
		//        ('routes' '(' routes+=[Route|EString] ( "," routes+=[Route|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Customer'
		//id=EString
		//'{'
		//    'name' name=EString
		//    'surname' surname=EString
		//    'email' email=EString
		//    ('subscriptionDate' subscriptionDate=EString)?
		//    'expirationDate' expirationDate=EString
		//    'status' status=CustomerStatus
		//    ('routes' '(' routes+=[Route|EString] ( "," routes+=[Route|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Customer'
		public Keyword getCustomerKeyword_0() { return cCustomerKeyword_0; }
		
		//id=EString
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_1_0() { return cIdEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'name'
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }
		
		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }
		
		//'surname'
		public Keyword getSurnameKeyword_5() { return cSurnameKeyword_5; }
		
		//surname=EString
		public Assignment getSurnameAssignment_6() { return cSurnameAssignment_6; }
		
		//EString
		public RuleCall getSurnameEStringParserRuleCall_6_0() { return cSurnameEStringParserRuleCall_6_0; }
		
		//'email'
		public Keyword getEmailKeyword_7() { return cEmailKeyword_7; }
		
		//email=EString
		public Assignment getEmailAssignment_8() { return cEmailAssignment_8; }
		
		//EString
		public RuleCall getEmailEStringParserRuleCall_8_0() { return cEmailEStringParserRuleCall_8_0; }
		
		//('subscriptionDate' subscriptionDate=EString)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'subscriptionDate'
		public Keyword getSubscriptionDateKeyword_9_0() { return cSubscriptionDateKeyword_9_0; }
		
		//subscriptionDate=EString
		public Assignment getSubscriptionDateAssignment_9_1() { return cSubscriptionDateAssignment_9_1; }
		
		//EString
		public RuleCall getSubscriptionDateEStringParserRuleCall_9_1_0() { return cSubscriptionDateEStringParserRuleCall_9_1_0; }
		
		//'expirationDate'
		public Keyword getExpirationDateKeyword_10() { return cExpirationDateKeyword_10; }
		
		//expirationDate=EString
		public Assignment getExpirationDateAssignment_11() { return cExpirationDateAssignment_11; }
		
		//EString
		public RuleCall getExpirationDateEStringParserRuleCall_11_0() { return cExpirationDateEStringParserRuleCall_11_0; }
		
		//'status'
		public Keyword getStatusKeyword_12() { return cStatusKeyword_12; }
		
		//status=CustomerStatus
		public Assignment getStatusAssignment_13() { return cStatusAssignment_13; }
		
		//CustomerStatus
		public RuleCall getStatusCustomerStatusEnumRuleCall_13_0() { return cStatusCustomerStatusEnumRuleCall_13_0; }
		
		//('routes' '(' routes+=[Route|EString] ( "," routes+=[Route|EString])* ')' )?
		public Group getGroup_14() { return cGroup_14; }
		
		//'routes'
		public Keyword getRoutesKeyword_14_0() { return cRoutesKeyword_14_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_14_1() { return cLeftParenthesisKeyword_14_1; }
		
		//routes+=[Route|EString]
		public Assignment getRoutesAssignment_14_2() { return cRoutesAssignment_14_2; }
		
		//[Route|EString]
		public CrossReference getRoutesRouteCrossReference_14_2_0() { return cRoutesRouteCrossReference_14_2_0; }
		
		//EString
		public RuleCall getRoutesRouteEStringParserRuleCall_14_2_0_1() { return cRoutesRouteEStringParserRuleCall_14_2_0_1; }
		
		//( "," routes+=[Route|EString])*
		public Group getGroup_14_3() { return cGroup_14_3; }
		
		//","
		public Keyword getCommaKeyword_14_3_0() { return cCommaKeyword_14_3_0; }
		
		//routes+=[Route|EString]
		public Assignment getRoutesAssignment_14_3_1() { return cRoutesAssignment_14_3_1; }
		
		//[Route|EString]
		public CrossReference getRoutesRouteCrossReference_14_3_1_0() { return cRoutesRouteCrossReference_14_3_1_0; }
		
		//EString
		public RuleCall getRoutesRouteEStringParserRuleCall_14_3_1_0_1() { return cRoutesRouteEStringParserRuleCall_14_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_14_4() { return cRightParenthesisKeyword_14_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class RiderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Rider");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRiderKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cSurnameKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSurnameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSurnameEStringParserRuleCall_6_0 = (RuleCall)cSurnameAssignment_6.eContents().get(0);
		private final Keyword cEmailKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cEmailAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cEmailEStringParserRuleCall_8_0 = (RuleCall)cEmailAssignment_8.eContents().get(0);
		private final Keyword cStatusKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cStatusAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cStatusRiderStatusEnumRuleCall_10_0 = (RuleCall)cStatusAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cRoutesKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cRoutesAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final CrossReference cRoutesRouteCrossReference_11_2_0 = (CrossReference)cRoutesAssignment_11_2.eContents().get(0);
		private final RuleCall cRoutesRouteEStringParserRuleCall_11_2_0_1 = (RuleCall)cRoutesRouteCrossReference_11_2_0.eContents().get(1);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cCommaKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Assignment cRoutesAssignment_11_3_1 = (Assignment)cGroup_11_3.eContents().get(1);
		private final CrossReference cRoutesRouteCrossReference_11_3_1_0 = (CrossReference)cRoutesAssignment_11_3_1.eContents().get(0);
		private final RuleCall cRoutesRouteEStringParserRuleCall_11_3_1_0_1 = (RuleCall)cRoutesRouteCrossReference_11_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cLivePositionKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cLivePositionAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cLivePositionGeolocationParserRuleCall_12_1_0 = (RuleCall)cLivePositionAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Rider returns Rider:
		//    'Rider'
		//    id=EString
		//    '{'
		//        'name' name=EString
		//        'surname' surname=EString
		//        'email' email=EString
		//        'status' status=RiderStatus
		//        ('routes' '(' routes+=[Route|EString] ( "," routes+=[Route|EString])* ')' )?
		//        ('livePosition' livePosition=Geolocation)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Rider'
		//id=EString
		//'{'
		//    'name' name=EString
		//    'surname' surname=EString
		//    'email' email=EString
		//    'status' status=RiderStatus
		//    ('routes' '(' routes+=[Route|EString] ( "," routes+=[Route|EString])* ')' )?
		//    ('livePosition' livePosition=Geolocation)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Rider'
		public Keyword getRiderKeyword_0() { return cRiderKeyword_0; }
		
		//id=EString
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_1_0() { return cIdEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'name'
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }
		
		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }
		
		//'surname'
		public Keyword getSurnameKeyword_5() { return cSurnameKeyword_5; }
		
		//surname=EString
		public Assignment getSurnameAssignment_6() { return cSurnameAssignment_6; }
		
		//EString
		public RuleCall getSurnameEStringParserRuleCall_6_0() { return cSurnameEStringParserRuleCall_6_0; }
		
		//'email'
		public Keyword getEmailKeyword_7() { return cEmailKeyword_7; }
		
		//email=EString
		public Assignment getEmailAssignment_8() { return cEmailAssignment_8; }
		
		//EString
		public RuleCall getEmailEStringParserRuleCall_8_0() { return cEmailEStringParserRuleCall_8_0; }
		
		//'status'
		public Keyword getStatusKeyword_9() { return cStatusKeyword_9; }
		
		//status=RiderStatus
		public Assignment getStatusAssignment_10() { return cStatusAssignment_10; }
		
		//RiderStatus
		public RuleCall getStatusRiderStatusEnumRuleCall_10_0() { return cStatusRiderStatusEnumRuleCall_10_0; }
		
		//('routes' '(' routes+=[Route|EString] ( "," routes+=[Route|EString])* ')' )?
		public Group getGroup_11() { return cGroup_11; }
		
		//'routes'
		public Keyword getRoutesKeyword_11_0() { return cRoutesKeyword_11_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_11_1() { return cLeftParenthesisKeyword_11_1; }
		
		//routes+=[Route|EString]
		public Assignment getRoutesAssignment_11_2() { return cRoutesAssignment_11_2; }
		
		//[Route|EString]
		public CrossReference getRoutesRouteCrossReference_11_2_0() { return cRoutesRouteCrossReference_11_2_0; }
		
		//EString
		public RuleCall getRoutesRouteEStringParserRuleCall_11_2_0_1() { return cRoutesRouteEStringParserRuleCall_11_2_0_1; }
		
		//( "," routes+=[Route|EString])*
		public Group getGroup_11_3() { return cGroup_11_3; }
		
		//","
		public Keyword getCommaKeyword_11_3_0() { return cCommaKeyword_11_3_0; }
		
		//routes+=[Route|EString]
		public Assignment getRoutesAssignment_11_3_1() { return cRoutesAssignment_11_3_1; }
		
		//[Route|EString]
		public CrossReference getRoutesRouteCrossReference_11_3_1_0() { return cRoutesRouteCrossReference_11_3_1_0; }
		
		//EString
		public RuleCall getRoutesRouteEStringParserRuleCall_11_3_1_0_1() { return cRoutesRouteEStringParserRuleCall_11_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_11_4() { return cRightParenthesisKeyword_11_4; }
		
		//('livePosition' livePosition=Geolocation)?
		public Group getGroup_12() { return cGroup_12; }
		
		//'livePosition'
		public Keyword getLivePositionKeyword_12_0() { return cLivePositionKeyword_12_0; }
		
		//livePosition=Geolocation
		public Assignment getLivePositionAssignment_12_1() { return cLivePositionAssignment_12_1; }
		
		//Geolocation
		public RuleCall getLivePositionGeolocationParserRuleCall_12_1_0() { return cLivePositionGeolocationParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class RouteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Route");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRouteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPriceKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPriceAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPriceEDoubleParserRuleCall_4_0 = (RuleCall)cPriceAssignment_4.eContents().get(0);
		private final Keyword cDateKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cDateAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cDateEStringParserRuleCall_6_0 = (RuleCall)cDateAssignment_6.eContents().get(0);
		private final Keyword cStartAddressKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cStartAddressAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cStartAddressEStringParserRuleCall_8_0 = (RuleCall)cStartAddressAssignment_8.eContents().get(0);
		private final Keyword cEndAddressKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cEndAddressAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cEndAddressEStringParserRuleCall_10_0 = (RuleCall)cEndAddressAssignment_10.eContents().get(0);
		private final Keyword cFeedbackKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cFeedbackAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cFeedbackEIntParserRuleCall_12_0 = (RuleCall)cFeedbackAssignment_12.eContents().get(0);
		private final Keyword cStatusKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cStatusAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cStatusRouteStatusEnumRuleCall_14_0 = (RuleCall)cStatusAssignment_14.eContents().get(0);
		private final Keyword cSeatKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cSeatAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cSeatEIntParserRuleCall_16_0 = (RuleCall)cSeatAssignment_16.eContents().get(0);
		private final Keyword cCustomerKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cCustomerAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final CrossReference cCustomerCustomerCrossReference_18_0 = (CrossReference)cCustomerAssignment_18.eContents().get(0);
		private final RuleCall cCustomerCustomerEStringParserRuleCall_18_0_1 = (RuleCall)cCustomerCustomerCrossReference_18_0.eContents().get(1);
		private final Keyword cRiderKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Assignment cRiderAssignment_20 = (Assignment)cGroup.eContents().get(20);
		private final CrossReference cRiderRiderCrossReference_20_0 = (CrossReference)cRiderAssignment_20.eContents().get(0);
		private final RuleCall cRiderRiderEStringParserRuleCall_20_0_1 = (RuleCall)cRiderRiderCrossReference_20_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_21 = (Keyword)cGroup.eContents().get(21);
		
		//Route returns Route:
		//    'Route'
		//    id=EString
		//    '{'
		//        'price' price=EDouble
		//        'date' date=EString
		//        'startAddress' startAddress=EString
		//        'endAddress' endAddress=EString
		//        'feedback' feedback=EInt
		//        'status' status=RouteStatus
		//        'seat' seat=EInt
		//        'customer' customer=[Customer|EString]
		//        'rider' rider=[Rider|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Route'
		//id=EString
		//'{'
		//    'price' price=EDouble
		//    'date' date=EString
		//    'startAddress' startAddress=EString
		//    'endAddress' endAddress=EString
		//    'feedback' feedback=EInt
		//    'status' status=RouteStatus
		//    'seat' seat=EInt
		//    'customer' customer=[Customer|EString]
		//    'rider' rider=[Rider|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Route'
		public Keyword getRouteKeyword_0() { return cRouteKeyword_0; }
		
		//id=EString
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_1_0() { return cIdEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'price'
		public Keyword getPriceKeyword_3() { return cPriceKeyword_3; }
		
		//price=EDouble
		public Assignment getPriceAssignment_4() { return cPriceAssignment_4; }
		
		//EDouble
		public RuleCall getPriceEDoubleParserRuleCall_4_0() { return cPriceEDoubleParserRuleCall_4_0; }
		
		//'date'
		public Keyword getDateKeyword_5() { return cDateKeyword_5; }
		
		//date=EString
		public Assignment getDateAssignment_6() { return cDateAssignment_6; }
		
		//EString
		public RuleCall getDateEStringParserRuleCall_6_0() { return cDateEStringParserRuleCall_6_0; }
		
		//'startAddress'
		public Keyword getStartAddressKeyword_7() { return cStartAddressKeyword_7; }
		
		//startAddress=EString
		public Assignment getStartAddressAssignment_8() { return cStartAddressAssignment_8; }
		
		//EString
		public RuleCall getStartAddressEStringParserRuleCall_8_0() { return cStartAddressEStringParserRuleCall_8_0; }
		
		//'endAddress'
		public Keyword getEndAddressKeyword_9() { return cEndAddressKeyword_9; }
		
		//endAddress=EString
		public Assignment getEndAddressAssignment_10() { return cEndAddressAssignment_10; }
		
		//EString
		public RuleCall getEndAddressEStringParserRuleCall_10_0() { return cEndAddressEStringParserRuleCall_10_0; }
		
		//'feedback'
		public Keyword getFeedbackKeyword_11() { return cFeedbackKeyword_11; }
		
		//feedback=EInt
		public Assignment getFeedbackAssignment_12() { return cFeedbackAssignment_12; }
		
		//EInt
		public RuleCall getFeedbackEIntParserRuleCall_12_0() { return cFeedbackEIntParserRuleCall_12_0; }
		
		//'status'
		public Keyword getStatusKeyword_13() { return cStatusKeyword_13; }
		
		//status=RouteStatus
		public Assignment getStatusAssignment_14() { return cStatusAssignment_14; }
		
		//RouteStatus
		public RuleCall getStatusRouteStatusEnumRuleCall_14_0() { return cStatusRouteStatusEnumRuleCall_14_0; }
		
		//'seat'
		public Keyword getSeatKeyword_15() { return cSeatKeyword_15; }
		
		//seat=EInt
		public Assignment getSeatAssignment_16() { return cSeatAssignment_16; }
		
		//EInt
		public RuleCall getSeatEIntParserRuleCall_16_0() { return cSeatEIntParserRuleCall_16_0; }
		
		//'customer'
		public Keyword getCustomerKeyword_17() { return cCustomerKeyword_17; }
		
		//customer=[Customer|EString]
		public Assignment getCustomerAssignment_18() { return cCustomerAssignment_18; }
		
		//[Customer|EString]
		public CrossReference getCustomerCustomerCrossReference_18_0() { return cCustomerCustomerCrossReference_18_0; }
		
		//EString
		public RuleCall getCustomerCustomerEStringParserRuleCall_18_0_1() { return cCustomerCustomerEStringParserRuleCall_18_0_1; }
		
		//'rider'
		public Keyword getRiderKeyword_19() { return cRiderKeyword_19; }
		
		//rider=[Rider|EString]
		public Assignment getRiderAssignment_20() { return cRiderAssignment_20; }
		
		//[Rider|EString]
		public CrossReference getRiderRiderCrossReference_20_0() { return cRiderRiderCrossReference_20_0; }
		
		//EString
		public RuleCall getRiderRiderEStringParserRuleCall_20_0_1() { return cRiderRiderEStringParserRuleCall_20_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_21() { return cRightCurlyBracketKeyword_21; }
	}
	public class GeolocationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Geolocation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGeolocationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLatKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLatAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLatEDoubleParserRuleCall_3_0 = (RuleCall)cLatAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLngKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLngAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLngEDoubleParserRuleCall_4_1_0 = (RuleCall)cLngAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Geolocation returns Geolocation:
		//    'Geolocation'
		//    '{'
		//        'lat' lat=EDouble
		//        ('lng' lng=EDouble)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Geolocation'
		//'{'
		//    'lat' lat=EDouble
		//    ('lng' lng=EDouble)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Geolocation'
		public Keyword getGeolocationKeyword_0() { return cGeolocationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'lat'
		public Keyword getLatKeyword_2() { return cLatKeyword_2; }
		
		//lat=EDouble
		public Assignment getLatAssignment_3() { return cLatAssignment_3; }
		
		//EDouble
		public RuleCall getLatEDoubleParserRuleCall_3_0() { return cLatEDoubleParserRuleCall_3_0; }
		
		//('lng' lng=EDouble)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'lng'
		public Keyword getLngKeyword_4_0() { return cLngKeyword_4_0; }
		
		//lng=EDouble
		public Assignment getLngAssignment_4_1() { return cLngAssignment_4_1; }
		
		//EDouble
		public RuleCall getLngEDoubleParserRuleCall_4_1_0() { return cLngEDoubleParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class CustomerStatusElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CustomerStatus");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPENDINGEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPENDINGPENDINGKeyword_0_0 = (Keyword)cPENDINGEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cACTIVEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cACTIVEDACTIVEDKeyword_1_0 = (Keyword)cACTIVEDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBANNEDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBANNEDBANNEDKeyword_2_0 = (Keyword)cBANNEDEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum CustomerStatus returns CustomerStatus:
		//                PENDING = 'PENDING' | ACTIVED = 'ACTIVED' | BANNED = 'BANNED';
		public EnumRule getRule() { return rule; }
		
		//PENDING = 'PENDING' | ACTIVED = 'ACTIVED' | BANNED = 'BANNED'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PENDING = 'PENDING'
		public EnumLiteralDeclaration getPENDINGEnumLiteralDeclaration_0() { return cPENDINGEnumLiteralDeclaration_0; }
		
		//'PENDING'
		public Keyword getPENDINGPENDINGKeyword_0_0() { return cPENDINGPENDINGKeyword_0_0; }
		
		//ACTIVED = 'ACTIVED'
		public EnumLiteralDeclaration getACTIVEDEnumLiteralDeclaration_1() { return cACTIVEDEnumLiteralDeclaration_1; }
		
		//'ACTIVED'
		public Keyword getACTIVEDACTIVEDKeyword_1_0() { return cACTIVEDACTIVEDKeyword_1_0; }
		
		//BANNED = 'BANNED'
		public EnumLiteralDeclaration getBANNEDEnumLiteralDeclaration_2() { return cBANNEDEnumLiteralDeclaration_2; }
		
		//'BANNED'
		public Keyword getBANNEDBANNEDKeyword_2_0() { return cBANNEDBANNEDKeyword_2_0; }
	}
	public class RiderStatusElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RiderStatus");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAVAILABLEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAVAILABLEAVAILABLEKeyword_0_0 = (Keyword)cAVAILABLEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBUSYEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBUSYBUSYKeyword_1_0 = (Keyword)cBUSYEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cUNAVAILABLEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cUNAVAILABLEUNAVAILABLEKeyword_2_0 = (Keyword)cUNAVAILABLEEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum RiderStatus returns RiderStatus:
		//                AVAILABLE = 'AVAILABLE' | BUSY = 'BUSY' | UNAVAILABLE = 'UNAVAILABLE';
		public EnumRule getRule() { return rule; }
		
		//AVAILABLE = 'AVAILABLE' | BUSY = 'BUSY' | UNAVAILABLE = 'UNAVAILABLE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AVAILABLE = 'AVAILABLE'
		public EnumLiteralDeclaration getAVAILABLEEnumLiteralDeclaration_0() { return cAVAILABLEEnumLiteralDeclaration_0; }
		
		//'AVAILABLE'
		public Keyword getAVAILABLEAVAILABLEKeyword_0_0() { return cAVAILABLEAVAILABLEKeyword_0_0; }
		
		//BUSY = 'BUSY'
		public EnumLiteralDeclaration getBUSYEnumLiteralDeclaration_1() { return cBUSYEnumLiteralDeclaration_1; }
		
		//'BUSY'
		public Keyword getBUSYBUSYKeyword_1_0() { return cBUSYBUSYKeyword_1_0; }
		
		//UNAVAILABLE = 'UNAVAILABLE'
		public EnumLiteralDeclaration getUNAVAILABLEEnumLiteralDeclaration_2() { return cUNAVAILABLEEnumLiteralDeclaration_2; }
		
		//'UNAVAILABLE'
		public Keyword getUNAVAILABLEUNAVAILABLEKeyword_2_0() { return cUNAVAILABLEUNAVAILABLEKeyword_2_0; }
	}
	public class RouteStatusElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RouteStatus");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDONEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDONEDONEKeyword_0_0 = (Keyword)cDONEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDOINGEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDOINGDOINGKeyword_1_0 = (Keyword)cDOINGEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPENDINGEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPENDINGPENDINGKeyword_2_0 = (Keyword)cPENDINGEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum RouteStatus returns RouteStatus:
		//                DONE = 'DONE' | DOING = 'DOING' | PENDING = 'PENDING';
		public EnumRule getRule() { return rule; }
		
		//DONE = 'DONE' | DOING = 'DOING' | PENDING = 'PENDING'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DONE = 'DONE'
		public EnumLiteralDeclaration getDONEEnumLiteralDeclaration_0() { return cDONEEnumLiteralDeclaration_0; }
		
		//'DONE'
		public Keyword getDONEDONEKeyword_0_0() { return cDONEDONEKeyword_0_0; }
		
		//DOING = 'DOING'
		public EnumLiteralDeclaration getDOINGEnumLiteralDeclaration_1() { return cDOINGEnumLiteralDeclaration_1; }
		
		//'DOING'
		public Keyword getDOINGDOINGKeyword_1_0() { return cDOINGDOINGKeyword_1_0; }
		
		//PENDING = 'PENDING'
		public EnumLiteralDeclaration getPENDINGEnumLiteralDeclaration_2() { return cPENDINGEnumLiteralDeclaration_2; }
		
		//'PENDING'
		public Keyword getPENDINGPENDINGKeyword_2_0() { return cPENDINGPENDINGKeyword_2_0; }
	}
	
	private final CompanyElements pCompany;
	private final EStringElements pEString;
	private final CustomerElements pCustomer;
	private final RiderElements pRider;
	private final RouteElements pRoute;
	private final CustomerStatusElements eCustomerStatus;
	private final RiderStatusElements eRiderStatus;
	private final GeolocationElements pGeolocation;
	private final EDoubleElements pEDouble;
	private final EIntElements pEInt;
	private final RouteStatusElements eRouteStatus;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pCompany = new CompanyElements();
		this.pEString = new EStringElements();
		this.pCustomer = new CustomerElements();
		this.pRider = new RiderElements();
		this.pRoute = new RouteElements();
		this.eCustomerStatus = new CustomerStatusElements();
		this.eRiderStatus = new RiderStatusElements();
		this.pGeolocation = new GeolocationElements();
		this.pEDouble = new EDoubleElements();
		this.pEInt = new EIntElements();
		this.eRouteStatus = new RouteStatusElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Company returns Company:
	//    {Company}
	//    'Company'
	//    name=EString
	//    '{'
	//        ('manager' manager=EString)?
	//        ('address' address=EString)?
	//        ('customers' '{' customers+=Customer ( "," customers+=Customer)* '}' )?
	//        ('riders' '{' riders+=Rider ( "," riders+=Rider)* '}' )?
	//        ('routes' '{' routes+=Route ( "," routes+=Route)* '}' )?
	//    '}';
	public CompanyElements getCompanyAccess() {
		return pCompany;
	}
	
	public ParserRule getCompanyRule() {
		return getCompanyAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Customer returns Customer:
	//    'Customer'
	//    id=EString
	//    '{'
	//        'name' name=EString
	//        'surname' surname=EString
	//        'email' email=EString
	//        ('subscriptionDate' subscriptionDate=EString)?
	//        'expirationDate' expirationDate=EString
	//        'status' status=CustomerStatus
	//        ('routes' '(' routes+=[Route|EString] ( "," routes+=[Route|EString])* ')' )?
	//    '}';
	public CustomerElements getCustomerAccess() {
		return pCustomer;
	}
	
	public ParserRule getCustomerRule() {
		return getCustomerAccess().getRule();
	}
	
	//Rider returns Rider:
	//    'Rider'
	//    id=EString
	//    '{'
	//        'name' name=EString
	//        'surname' surname=EString
	//        'email' email=EString
	//        'status' status=RiderStatus
	//        ('routes' '(' routes+=[Route|EString] ( "," routes+=[Route|EString])* ')' )?
	//        ('livePosition' livePosition=Geolocation)?
	//    '}';
	public RiderElements getRiderAccess() {
		return pRider;
	}
	
	public ParserRule getRiderRule() {
		return getRiderAccess().getRule();
	}
	
	//Route returns Route:
	//    'Route'
	//    id=EString
	//    '{'
	//        'price' price=EDouble
	//        'date' date=EString
	//        'startAddress' startAddress=EString
	//        'endAddress' endAddress=EString
	//        'feedback' feedback=EInt
	//        'status' status=RouteStatus
	//        'seat' seat=EInt
	//        'customer' customer=[Customer|EString]
	//        'rider' rider=[Rider|EString]
	//    '}';
	public RouteElements getRouteAccess() {
		return pRoute;
	}
	
	public ParserRule getRouteRule() {
		return getRouteAccess().getRule();
	}
	
	//enum CustomerStatus returns CustomerStatus:
	//                PENDING = 'PENDING' | ACTIVED = 'ACTIVED' | BANNED = 'BANNED';
	public CustomerStatusElements getCustomerStatusAccess() {
		return eCustomerStatus;
	}
	
	public EnumRule getCustomerStatusRule() {
		return getCustomerStatusAccess().getRule();
	}
	
	//enum RiderStatus returns RiderStatus:
	//                AVAILABLE = 'AVAILABLE' | BUSY = 'BUSY' | UNAVAILABLE = 'UNAVAILABLE';
	public RiderStatusElements getRiderStatusAccess() {
		return eRiderStatus;
	}
	
	public EnumRule getRiderStatusRule() {
		return getRiderStatusAccess().getRule();
	}
	
	//Geolocation returns Geolocation:
	//    'Geolocation'
	//    '{'
	//        'lat' lat=EDouble
	//        ('lng' lng=EDouble)?
	//    '}';
	public GeolocationElements getGeolocationAccess() {
		return pGeolocation;
	}
	
	public ParserRule getGeolocationRule() {
		return getGeolocationAccess().getRule();
	}
	
	//EDouble returns ecore::EDouble:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//enum RouteStatus returns RouteStatus:
	//                DONE = 'DONE' | DOING = 'DOING' | PENDING = 'PENDING';
	public RouteStatusElements getRouteStatusAccess() {
		return eRouteStatus;
	}
	
	public EnumRule getRouteStatusRule() {
		return getRouteStatusAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
