package ADSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_RouteStatus extends EnumerationDescriptorBase {

  public EnumerationDescriptor_RouteStatus() {
    super(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb561887L, "RouteStatus", "r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915242119");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_DONE_0 = new EnumerationDescriptor.MemberDescriptor("DONE", "DONE", 0x4ed7adb2eb561888L, "r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915242120");
  private final EnumerationDescriptor.MemberDescriptor myMember_DOING_0 = new EnumerationDescriptor.MemberDescriptor("DOING", "DOING", 0x4ed7adb2eb561889L, "r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915242121");
  private final EnumerationDescriptor.MemberDescriptor myMember_PENDING_0 = new EnumerationDescriptor.MemberDescriptor("PENDING", "PENDING", 0x4ed7adb2eb56188cL, "r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915242124");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb561887L, 0x4ed7adb2eb561888L, 0x4ed7adb2eb561889L, 0x4ed7adb2eb56188cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_DONE_0, myMember_DOING_0, myMember_PENDING_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "DONE":
        return myMember_DONE_0;
      case "DOING":
        return myMember_DOING_0;
      case "PENDING":
        return myMember_PENDING_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
