package ADSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CustomerStatus extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CustomerStatus() {
    super(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb5617aeL, "CustomerStatus", "r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915241902");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_PENDING_0 = new EnumerationDescriptor.MemberDescriptor("PENDING", "PENDING", 0x4ed7adb2eb5617afL, "r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915241903");
  private final EnumerationDescriptor.MemberDescriptor myMember_ACTIVED_0 = new EnumerationDescriptor.MemberDescriptor("ACTIVED", "ACTIVED", 0x4ed7adb2eb5617b0L, "r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915241904");
  private final EnumerationDescriptor.MemberDescriptor myMember_BANNED_0 = new EnumerationDescriptor.MemberDescriptor("BANNED", "BANNED", 0x4ed7adb2eb5617b3L, "r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915241907");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb5617aeL, 0x4ed7adb2eb5617afL, 0x4ed7adb2eb5617b0L, 0x4ed7adb2eb5617b3L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_PENDING_0, myMember_ACTIVED_0, myMember_BANNED_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "PENDING":
        return myMember_PENDING_0;
      case "ACTIVED":
        return myMember_ACTIVED_0;
      case "BANNED":
        return myMember_BANNED_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
