package ADSL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int CardId = 0;
  public static final int Customer = 1;
  public static final int Geolocation = 2;
  public static final int Rider = 3;
  public static final int Route = 4;
  public static final int System = 5;
  public static final int User = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL);
    builder.put(0x4ed7adb2eb5618d9L, CardId);
    builder.put(0x4ed7adb2eb5617adL, Customer);
    builder.put(0x4ed7adb2eb561a1eL, Geolocation);
    builder.put(0x4ed7adb2eb5617b9L, Rider);
    builder.put(0x4ed7adb2eb561881L, Route);
    builder.put(0x4ed7adb2eb547471L, System);
    builder.put(0x4ed7adb2eb55230eL, User);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
