package ADSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptorImpl;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCardId = createDescriptorForCardId();
  /*package*/ final ConceptDescriptor myConceptCustomer = createDescriptorForCustomer();
  /*package*/ final ConceptDescriptor myConceptGeolocation = createDescriptorForGeolocation();
  /*package*/ final ConceptDescriptor myConceptRider = createDescriptorForRider();
  /*package*/ final ConceptDescriptor myConceptRoute = createDescriptorForRoute();
  /*package*/ final ConceptDescriptor myConceptSystem = createDescriptorForSystem();
  /*package*/ final ConceptDescriptor myConceptUser = createDescriptorForUser();
  /*package*/ final EnumerationDescriptor myEnumerationCustomerStatus = new EnumerationDescriptor_CustomerStatus();
  /*package*/ final EnumerationDescriptor myEnumerationRiderStatus = new EnumerationDescriptor_RiderStatus();
  /*package*/ final EnumerationDescriptor myEnumerationRouteStatus = new EnumerationDescriptor_RouteStatus();
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypedate = new ConstrainedStringDatatypeDescriptorImpl(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb58015cL, "date", "r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915367260", "(([1-2][0-9])|([1-9])|(3[0-1]))/((1[0-2])|([1-9]))/[0-9]{4}");
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCardId, myConceptCustomer, myConceptGeolocation, myConceptRider, myConceptRoute, myConceptSystem, myConceptUser);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.CardId:
        return myConceptCardId;
      case LanguageConceptSwitch.Customer:
        return myConceptCustomer;
      case LanguageConceptSwitch.Geolocation:
        return myConceptGeolocation;
      case LanguageConceptSwitch.Rider:
        return myConceptRider;
      case LanguageConceptSwitch.Route:
        return myConceptRoute;
      case LanguageConceptSwitch.System:
        return myConceptSystem;
      case LanguageConceptSwitch.User:
        return myConceptUser;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationCustomerStatus, myEnumerationRiderStatus, myEnumerationRouteStatus, myCSDatatypedate);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCardId() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ADSL", "CardId", 0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb5618d9L);
    b.class_(false, false, false);
    b.origin("r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915242201");
    b.version(2);
    b.property("id", 0x4ed7adb2eb5618daL).type(PrimitiveTypeId.STRING).origin("5681200438915242202").done();
    b.property("path", 0x4ed7adb2eb5618e0L).type(PrimitiveTypeId.STRING).origin("5681200438915242208").done();
    b.property("birthdate", 0x4ed7adb2eb5618efL).type(PrimitiveTypeId.STRING).origin("5681200438915242223").done();
    b.property("expirationDate", 0x4ed7adb2eb561901L).type(PrimitiveTypeId.STRING).origin("5681200438915242241").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCustomer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ADSL", "Customer", 0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb5617adL);
    b.class_(false, false, true);
    b.super_("ADSL.structure.User", 0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb55230eL);
    b.origin("r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915241901");
    b.version(2);
    b.property("status", 0x4ed7adb2eb5617b7L).type(MetaIdFactory.dataTypeId(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb5617aeL)).origin("5681200438915241911").done();
    b.aggregate("cardId", 0x4ed7adb2eb561910L).target(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb5618d9L).optional(false).ordered(true).multiple(false).origin("5681200438915242256").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGeolocation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ADSL", "Geolocation", 0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb561a1eL);
    b.class_(false, false, false);
    b.origin("r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915242526");
    b.version(2);
    b.property("lat", 0x4ed7adb2eb561a1fL).type(PrimitiveTypeId.INTEGER).origin("5681200438915242527").done();
    b.property("lng", 0x4ed7adb2eb561a21L).type(PrimitiveTypeId.INTEGER).origin("5681200438915242529").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRider() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ADSL", "Rider", 0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb5617b9L);
    b.class_(false, false, true);
    b.super_("ADSL.structure.User", 0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb55230eL);
    b.origin("r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915241913");
    b.version(2);
    b.property("status", 0x4ed7adb2eb5617c5L).type(MetaIdFactory.dataTypeId(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb5617baL)).origin("5681200438915241925").done();
    b.aggregate("livePosition", 0x4ed7adb2eb561a24L).target(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb561a1eL).optional(true).ordered(true).multiple(false).origin("5681200438915242532").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRoute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ADSL", "Route", 0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb561881L);
    b.class_(false, false, false);
    b.origin("r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915242113");
    b.version(2);
    b.property("id", 0x4ed7adb2eb561882L).type(PrimitiveTypeId.STRING).origin("5681200438915242114").done();
    b.property("status", 0x4ed7adb2eb561884L).type(MetaIdFactory.dataTypeId(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb561887L)).origin("5681200438915242116").done();
    b.property("price", 0x4ed7adb2eb561890L).type(PrimitiveTypeId.INTEGER).origin("5681200438915242128").done();
    b.property("date", 0x4ed7adb2eb561894L).type(MetaIdFactory.dataTypeId(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb58015cL)).origin("5681200438915242132").done();
    b.property("km", 0x4ed7adb2eb561899L).type(PrimitiveTypeId.INTEGER).origin("5681200438915242137").done();
    b.property("startAddress", 0x4ed7adb2eb5618caL).type(PrimitiveTypeId.STRING).origin("5681200438915242186").done();
    b.property("endAddress", 0x4ed7adb2eb5618d1L).type(PrimitiveTypeId.STRING).origin("5681200438915242193").done();
    b.aggregate("customer", 0x4ed7adb2eb5618c1L).target(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb5617adL).optional(false).ordered(true).multiple(false).origin("5681200438915242177").done();
    b.aggregate("rider", 0x4ed7adb2eb5618c7L).target(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb5617b9L).optional(true).ordered(true).multiple(false).origin("5681200438915242183").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSystem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ADSL", "System", 0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb547471L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915134577");
    b.version(2);
    b.property("author", 0x4ed7adb2eb547476L).type(PrimitiveTypeId.STRING).origin("5681200438915134582").done();
    b.property("version", 0x4ed7adb2eb547478L).type(PrimitiveTypeId.STRING).origin("5681200438915134584").done();
    b.aggregate("routes", 0x4ed7adb2eb552384L).target(0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb561881L).optional(false).ordered(true).multiple(true).origin("5681200438915179396").done();
    b.alias("Root");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUser() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ADSL", "User", 0x5c9a0e652f1e4e9aL, 0xadf18dcc826f515fL, 0x4ed7adb2eb55230eL);
    b.class_(false, true, false);
    b.origin("r:f31c5c66-7689-442d-abb8-ca332c02cb22(ADSL.structure)/5681200438915179278");
    b.version(2);
    b.property("id", 0x4ed7adb2eb552311L).type(PrimitiveTypeId.STRING).origin("5681200438915179281").done();
    b.property("name", 0x4ed7adb2eb552329L).type(PrimitiveTypeId.STRING).origin("5681200438915179305").done();
    b.property("surname", 0x4ed7adb2eb552316L).type(PrimitiveTypeId.STRING).origin("5681200438915179286").done();
    b.property("email", 0x4ed7adb2eb55231fL).type(PrimitiveTypeId.STRING).origin("5681200438915179295").done();
    b.property("password", 0x4ed7adb2eb55231aL).type(PrimitiveTypeId.STRING).origin("5681200438915179290").done();
    b.property("phone", 0x4ed7adb2eb556f94L).type(PrimitiveTypeId.STRING).origin("5681200438915198868").done();
    return b.create();
  }
}
