/**
 *
 * $Id$
 */
package it.disim.loreand.mde.validation;

import it.disim.loreand.mde.CustomerStatus;
import it.disim.loreand.mde.Route;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link it.disim.loreand.mde.Customer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CustomerValidator {
	boolean validate();

	boolean validateSubscriptionDate(Date value);

	boolean validateExpirationDate(Date value);

	boolean validateStatus(CustomerStatus value);

	boolean validateRoutes(EList<Route> value);
}
