/**
 *
 * $Id$
 */
package it.disim.loreand.mde.validation;

import it.disim.loreand.mde.Customer;
import it.disim.loreand.mde.Rider;
import it.disim.loreand.mde.Route;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link it.disim.loreand.mde.Uber}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UberValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateManager(String value);

	boolean validateAddress(String value);

	boolean validateCustomers(EList<Customer> value);

	boolean validateRiders(EList<Rider> value);

	boolean validateRoutes(EList<Route> value);
}
