/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;
import taxi.Company;
import taxi.Customer;
import taxi.Geolocation;
import taxi.Rider;
import taxi.Route;
import taxi.TaxiPackage;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == TaxiPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TaxiPackage.COMPANY:
				sequence_Company(context, (Company) semanticObject); 
				return; 
			case TaxiPackage.CUSTOMER:
				sequence_Customer(context, (Customer) semanticObject); 
				return; 
			case TaxiPackage.GEOLOCATION:
				sequence_Geolocation(context, (Geolocation) semanticObject); 
				return; 
			case TaxiPackage.RIDER:
				sequence_Rider(context, (Rider) semanticObject); 
				return; 
			case TaxiPackage.ROUTE:
				sequence_Route(context, (Route) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Company returns Company
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         manager=EString? 
	 *         address=EString? 
	 *         (customers+=Customer customers+=Customer*)? 
	 *         (riders+=Rider riders+=Rider*)? 
	 *         (routes+=Route routes+=Route*)?
	 *     )
	 */
	protected void sequence_Company(ISerializationContext context, Company semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Customer returns Customer
	 *
	 * Constraint:
	 *     (
	 *         id=EString 
	 *         name=EString 
	 *         surname=EString 
	 *         email=EString 
	 *         subscriptionDate=EString? 
	 *         expirationDate=EString 
	 *         status=CustomerStatus 
	 *         (routes+=[Route|EString] routes+=[Route|EString]*)?
	 *     )
	 */
	protected void sequence_Customer(ISerializationContext context, Customer semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Geolocation returns Geolocation
	 *
	 * Constraint:
	 *     (lat=EDouble lng=EDouble?)
	 */
	protected void sequence_Geolocation(ISerializationContext context, Geolocation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Rider returns Rider
	 *
	 * Constraint:
	 *     (
	 *         id=EString 
	 *         name=EString 
	 *         surname=EString 
	 *         email=EString 
	 *         status=RiderStatus 
	 *         (routes+=[Route|EString] routes+=[Route|EString]*)? 
	 *         livePosition=Geolocation?
	 *     )
	 */
	protected void sequence_Rider(ISerializationContext context, Rider semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Route returns Route
	 *
	 * Constraint:
	 *     (
	 *         id=EString 
	 *         price=EDouble 
	 *         date=EString 
	 *         startAddress=EString 
	 *         endAddress=EString 
	 *         feedback=EInt 
	 *         status=RouteStatus 
	 *         seat=EInt 
	 *         customer=[Customer|EString] 
	 *         rider=[Rider|EString]
	 *     )
	 */
	protected void sequence_Route(ISerializationContext context, Route semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TaxiPackage.Literals.IDENTIFIABLE__ID) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TaxiPackage.Literals.IDENTIFIABLE__ID));
			if (transientValues.isValueTransient(semanticObject, TaxiPackage.Literals.ROUTE__PRICE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TaxiPackage.Literals.ROUTE__PRICE));
			if (transientValues.isValueTransient(semanticObject, TaxiPackage.Literals.ROUTE__DATE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TaxiPackage.Literals.ROUTE__DATE));
			if (transientValues.isValueTransient(semanticObject, TaxiPackage.Literals.ROUTE__START_ADDRESS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TaxiPackage.Literals.ROUTE__START_ADDRESS));
			if (transientValues.isValueTransient(semanticObject, TaxiPackage.Literals.ROUTE__END_ADDRESS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TaxiPackage.Literals.ROUTE__END_ADDRESS));
			if (transientValues.isValueTransient(semanticObject, TaxiPackage.Literals.ROUTE__FEEDBACK) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TaxiPackage.Literals.ROUTE__FEEDBACK));
			if (transientValues.isValueTransient(semanticObject, TaxiPackage.Literals.ROUTE__STATUS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TaxiPackage.Literals.ROUTE__STATUS));
			if (transientValues.isValueTransient(semanticObject, TaxiPackage.Literals.ROUTE__SEAT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TaxiPackage.Literals.ROUTE__SEAT));
			if (transientValues.isValueTransient(semanticObject, TaxiPackage.Literals.ROUTE__CUSTOMER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TaxiPackage.Literals.ROUTE__CUSTOMER));
			if (transientValues.isValueTransient(semanticObject, TaxiPackage.Literals.ROUTE__RIDER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TaxiPackage.Literals.ROUTE__RIDER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRouteAccess().getIdEStringParserRuleCall_1_0(), semanticObject.getId());
		feeder.accept(grammarAccess.getRouteAccess().getPriceEDoubleParserRuleCall_4_0(), semanticObject.getPrice());
		feeder.accept(grammarAccess.getRouteAccess().getDateEStringParserRuleCall_6_0(), semanticObject.getDate());
		feeder.accept(grammarAccess.getRouteAccess().getStartAddressEStringParserRuleCall_8_0(), semanticObject.getStartAddress());
		feeder.accept(grammarAccess.getRouteAccess().getEndAddressEStringParserRuleCall_10_0(), semanticObject.getEndAddress());
		feeder.accept(grammarAccess.getRouteAccess().getFeedbackEIntParserRuleCall_12_0(), semanticObject.getFeedback());
		feeder.accept(grammarAccess.getRouteAccess().getStatusRouteStatusEnumRuleCall_14_0(), semanticObject.getStatus());
		feeder.accept(grammarAccess.getRouteAccess().getSeatEIntParserRuleCall_16_0(), semanticObject.getSeat());
		feeder.accept(grammarAccess.getRouteAccess().getCustomerCustomerEStringParserRuleCall_18_0_1(), semanticObject.eGet(TaxiPackage.Literals.ROUTE__CUSTOMER, false));
		feeder.accept(grammarAccess.getRouteAccess().getRiderRiderEStringParserRuleCall_20_0_1(), semanticObject.eGet(TaxiPackage.Literals.ROUTE__RIDER, false));
		feeder.finish();
	}
	
	
}
