/**
 *
 * $Id$
 */
package uber.validation;

import org.eclipse.emf.common.util.EList;

import uber.Customer;
import uber.Rider;
import uber.Route;

/**
 * A sample validator interface for {@link uber.Company}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CompanyValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateManager(String value);

	boolean validateAddress(String value);

	boolean validateCustomers(EList<Customer> value);

	boolean validateRiders(EList<Rider> value);

	boolean validateRoutes(EList<Route> value);
}
