/**
 *
 * $Id$
 */
package uber.validation;

import org.eclipse.emf.common.util.EList;

import uber.Geolocation;
import uber.RiderStatus;
import uber.Route;

/**
 * A sample validator interface for {@link uber.Rider}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RiderValidator {
	boolean validate();

	boolean validateStatus(RiderStatus value);

	boolean validateLivePosition(Geolocation value);

	boolean validateRoutes(EList<Route> value);
}
