/**
 *
 * $Id$
 */
package uber.validation;

import java.util.Date;

import uber.Customer;
import uber.Rider;
import uber.RouteStatus;

/**
 * A sample validator interface for {@link uber.Route}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RouteValidator {
	boolean validate();

	boolean validatePrice(double value);

	boolean validateDate(Date value);

	boolean validateStartAddress(String value);

	boolean validateEndAddress(String value);

	boolean validateFeedback(int value);

	boolean validateStatus(RouteStatus value);

	boolean validateCustomer(Customer value);

	boolean validateRider(Rider value);

	boolean validateSeat(int value);
}
