/*
 * generated by Xtext 2.25.0
 */
package it.disim.mde.loreand.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUberDslScopeProvider extends DelegatingScopeProvider {
}
