/**
 *
 * $Id$
 */
package taxi.validation;

import org.eclipse.emf.common.util.EList;

import taxi.CustomerStatus;
import taxi.Route;

/**
 * A sample validator interface for {@link taxi.Customer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CustomerValidator {
	boolean validate();

	boolean validateSubscriptionDate(String value);
	boolean validateExpirationDate(String value);
	boolean validateStatus(CustomerStatus value);
	boolean validateRoutes(EList<Route> value);
}
