/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl1.formatting2;

import com.google.inject.Inject;
import it.disim.loreand.mde.Geolocation;
import it.disim.loreand.mde.Rider;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.example.mydsl1.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;
  
  protected void _format(final Rider rider, @Extension final IFormattableDocument document) {
    document.<Geolocation>format(rider.getLocation());
  }
  
  public void format(final Object rider, final IFormattableDocument document) {
    if (rider instanceof Rider) {
      _format((Rider)rider, document);
      return;
    } else if (rider instanceof XtextResource) {
      _format((XtextResource)rider, document);
      return;
    } else if (rider instanceof EObject) {
      _format((EObject)rider, document);
      return;
    } else if (rider == null) {
      _format((Void)null, document);
      return;
    } else if (rider != null) {
      _format(rider, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(rider, document).toString());
    }
  }
}
