/**
 *
 * $Id$
 */
package it.disim.mde.loreand.uber.validation;

import it.disim.mde.loreand.uber.Supervisor;

/**
 * A sample validator interface for {@link it.disim.mde.loreand.uber.CardID}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CardIDValidator {
	boolean validate();

	boolean validatePath(String value);

	boolean validateReleaseDate(String value);

	boolean validateInstitution(String value);

	boolean validateApproved(Supervisor value);
}
