/**
 *
 * $Id$
 */
package it.disim.mde.loreand.uber.validation;

import it.disim.mde.loreand.uber.Car;
import it.disim.mde.loreand.uber.Geolocation;
import it.disim.mde.loreand.uber.RiderStatus;
import it.disim.mde.loreand.uber.Route;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link it.disim.mde.loreand.uber.Rider}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RiderValidator {
	boolean validate();

	boolean validateStatus(RiderStatus value);

	boolean validateLocation(Geolocation value);

	boolean validateRoutes(EList<Route> value);

	boolean validateCarriedOutRoutes(int value);

	boolean validateScore(double value);

	boolean validateCar(Car value);
}
