/*
 * generated by Xtext 2.25.0
 */
package it.disim.mde.loreand.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UberDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/disim/mde/loreand/xtext/parser/antlr/internal/InternalUberDsl.tokens");
	}
}
