/*
 * generated by Xtext 2.25.0
 */
package it.disim.mde.loreand.xtext.parser.antlr;

import com.google.inject.Inject;
import it.disim.mde.loreand.xtext.parser.antlr.internal.InternalUberDslParser;
import it.disim.mde.loreand.xtext.services.UberDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class UberDslParser extends AbstractAntlrParser {

	@Inject
	private UberDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUberDslParser createParser(XtextTokenStream stream) {
		return new InternalUberDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Uber";
	}

	public UberDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UberDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
